### ISSUE TITLE
You can glitch through walls sometimes

### ISSUE THREAD

**Issue by ScanuNicco** [ScanuNicco/Boat-Race#18]
It is just finicky enough to get through the wall but just good enough to make it hard to get back in.

**Comment by zorbulator** [comment]
More specifically turning isnt effecTed bY collision

On Jan 12, 2019 3:17 PM, "scanunicco" <notifications@github.com> wrote:

Assigned #18 <https://github.com/ScanuNicco/Boat-Race/issues/18> to
@zorbulator <https://github.com/zorbulator>.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/ScanuNicco/Boat-Race/issues/18#event-2070306513>, or mute
the thread

**Comment by zorbulator** [comment]
To fix this more, we should program the boat to completely move away from the object when it collides and also add an acceleration system to turning like with moving to make turning better and collisions with turning better.

**Comment by zorbulator** [comment]
This only really happens with the angled surfaces now, see #37.
