### ISSUE TITLE
What are these?

### ISSUE THREAD

**Issue by zorbulator** [ScanuNicco/Boat-Race#27]
These are all over the place in only one track and I can't tell what they are supposed to be. If they are something from venice can you show me a picture, otherwise why are they here? (The walls right in the middle)

![image](https://user-images.githubusercontent.com/25832911/51634867-2e64c200-1f0a-11e9-8ff7-2e55b12c0099.png)

**Comment by ScanuNicco** [comment]
In venice there are lots of canals, not just one. I added lots of canals to the track so it would look like venice. Because this is a racing game I had to block off extra canals to make a track. The wall things are placeholders until I can find something better (possibly gondolas) to block off extra canals

**Comment by zorbulator** [comment]
That makes sense but you should use this to have all the tracks be one object (at least a similar object with different blocker locations) by blocking off the parts that aren't used instead of having completely separate tracks with blocked-off areas you can never go to
